tipo = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'. format(type(tipo)))
print('Só tem espaço? {}'.format(tipo.isspace()))
print('É um numeral? {}'.format(tipo.isnumeric()))
print('É alfabético? {}'.format(tipo.isalpha()))
print('É alfanumérico? {}'.format(tipo.isalnum()))
print('É maiúsculo? {}'.format(tipo.isupper()))
print('É minúsculo? {}'.format(tipo.islower()))
print('Esta Capitalizado? {}'. format(tipo.istitle()))
